### ISSUE TITLE
Feature Request: Mouse and keyboard support for desktop view

### ISSUE THREAD

**Issue by marklcrns** [phentos/scratchpad#1]
Would be nice to have support for mouse events and keyboard shortcuts :)

**Comment by phentos** [comment]
### Proposed keybinds
- [x] Hold shift to ~~temporarily toggle~~ strobe invert state
- [x] Tap shift to swap invert state
- [x] fla(t)
- [x] (f)an
- [x] (d)ots
- [x] (c)ircles

### Mouse behavior
- [x] Left click for `FG_COLOR` ~~, right click for `BG_COLOR`~~
- [ ] ~~Scroll wheel to adjust size thingy~~

**Comment by marklcrns** [comment]
Support for 'CTRL + z' and  'CTRL + SHIFT + z' for undo/redo strokes would be nice.
